generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      OppPoliticianHistoryCache
    theme:            default
    css:              my_generator
    
    fields:
      ramo_filter:   { name: "Ramo" }

    list:
      title:          Elenco ...
      display:        [data, indice, chi_id, _chi, created_at]
      filters:        [_ramo_filter, chi_tipo, data]
