generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      OppPoliticianHistoryCache
    theme:            default
    css:              my_generator
    
    fields:
      ramo_filter:   { name: "Ramo" }

    list:
      title:          Elenco ...
      display:        [data, assenze, presenze, missioni, indice, ribellioni, votazioni, _chi, ramo, created_at, updated_at]
      filters:        [_ramo_filter]
