# default values
all:
  sfSimpleBlog:
    user_class:          OppUser
    use_bundled_layout:  false

  # remote guard host
  remote_guard_host:      'lapgu.guard.openpolis.it'
  #remote_guard_host:      'accesso.openpolis.it'

  # cookies
  cookies:
    path:                 '/'
    domain:               'openpolis.it'
    sso_name:             'opSSO'
    remember_name:        'opRemember'
    remember_key_expiration_age: 604800 # (7 days)
