<?php require_once(SF_ROOT_DIR.DIRECTORY_SEPARATOR.'config'.DIRECTORY_SEPARATOR.'variables_selector.php'); ?>

# default values
all:
  sfSimpleBlog:
    user_class:          OppUser
    use_bundled_layout:  false
    use_rich_text:       true
    use_media_library:   true

  sfMediaLibrary:
#    upload_dir: upload/assets        # directory di default per l'upload

  # cookies
  cookies:
    path:                 '/'
    domain:               'openpolis.it'
    sso_name:             'opSSO'
    remember_name:        'opRemember'
    remember_key_expiration_age: 604800 # (7 days)
