<?php require_once(SF_ROOT_DIR.DIRECTORY_SEPARATOR.'config'.DIRECTORY_SEPARATOR.'variables_selector.php'); ?>

# default values
all:
  remote_guard_host:      '<?php echo $remote_guard_host ?>'
  site_url:               '<?php echo $site_url ?>'

  sfSimpleBlog:
    user_class:          OppUser
    use_bundled_layout:  false


  # cookies
  cookies:
    path:                 '/'
    domain:               'openpolis.it'
    sso_name:             'opSSO'
    remember_name:        'opRemember'
    remember_key_expiration_age: 604800 # (7 days)
