<?php
if (array_key_exists('SERVER_NAME', $_SERVER))
{
  if ($_SERVER['SERVER_NAME'] == 'lapgu.parlamento.openpolis.it') {
    $site_url = 'lapgu.parlamento.openpolis.it';
    $remote_guard_host = 'lapgu.guard.openpolis.it';
  } else if ($_SERVER['SERVER_NAME'] == 'openparlamento.depplab.net') {
    $site_url = 'openparlamento.depplab.net';
    $remote_guard_host = 'accesso.openpolis.it';
  } else if ($_SERVER['SERVER_NAME'] == 'parlamento.openpolis.it') {
    $site_url = 'parlamento.openpolis.it';
    $remote_guard_host = 'accesso.openpolis.it';  
  }
} else {
  $site_url = '';
  $remote_guard_host = '';
}
?>

# default values
all:
  remote_guard_host:      '<?php echo $remote_guard_host ?>'
  site_url:               '<?php echo $site_url ?>'

  sfSimpleBlog:
    user_class:          OppUser
    use_bundled_layout:  false


  # cookies
  cookies:
    path:                 '/'
    domain:               'openpolis.it'
    sso_name:             'opSSO'
    remember_name:        'opRemember'
    remember_key_expiration_age: 604800 # (7 days)
