# default rules
blog_posts:
  url:   /blog_posts
  param: { module: sfSimpleBlogPostAdmin, action: index }

blog_comments:
  url:   /blog_comments
  param: { module: sfSimpleBlogCommentAdmin, action: index }
  
homepage:
  url:   /
  param: { module: tag, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
