categorie:
  url:  /categorie
  param: { module: teseott, action: index }

argomenti:
  url:  /argomenti
  param: { module: tag, action: index }

blog_posts:
  url:   /blog_posts
  param: { module: sfSimpleBlogPostAdmin, action: index }

blog_comments:
  url:   /blog_comments
  param: { module: sfSimpleBlogCommentAdmin, action: index }
  
supra_variables:
  url:  /supra_variables
  param: { module: sfSupraVariablesAdmin, action: index }
  
# default rules
homepage:
  url:   /
  param: { module: tag, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
