default:
  http_metas:
    content-type: text/html

  metas:
    title:        Area riservata Openparlamento
    robots:       noindex,nofollow
    googlebot:    noarchive,nosnippet
    description:  Il progetto Openpolis per il monitoring del Parlamento
    keywords:     Openparlamento, Openpolis, monitoring parlamentare, monitoring parlamento, controllo parlamentare, controllo parlamento
    language:     it

  stylesheets:    [admin]

  javascripts:    []

  has_layout:     on
  layout:         layout
