default:
  http_metas:
    content-type: text/html

  metas:
    title:        OPENPARLAMENTO
    robots:       index, follow
    description:  Un progetto di Openpolis
    keywords:     Openparlamento, Openpolis
    language:     it

  stylesheets:    [main]

  javascripts:    []

  has_layout:     on
  layout:         layout
