listSuccess:
  javascripts:    [fe/jquery-1.2.6.pack.js, fe/jquery.morelazyload.js, fe/jquery.combobox.js, fe/jquery.pngFix.js, fe/openparlamento.lists.js]

default:
  javascripts:    [fe/jquery-1.2.6.pack.js, fe/jquery.combobox.js, fe/jquery.pngFix.js, fe/openparlamento.lists.js]
