interessiSuccess:
  metas:
    title:        "OpenParlamento - interessi dei parlamentari"
    description: "dati storici su interessi dei parlamentari"
  javascripts:    [fe/jquery.bgiframe.min.js, fe/jquery.ajaxQueue.js, fe/jquery.autocomplete.min.js]
  stylesheets:    [monitoring, jquery.autocomplete.css]
  

rilevanzaSuccess:
  metas:
    title:        "OpenParlamento - dati storici rilevanza atti"
    description: "dati storici sulla rilevanza degli atti"

presenzeSuccess:
  metas:
    title:        "OpenParlamento - dati storici presenze assenze e missioni"
    description: "dati storici su presenze, assenze e missioni"

indiceSuccess:
  metas:
    title:        "OpenParlamento - dati storici indice attivit&agrave;"
    description: "dati storici su indice attivit&agrave;"

all:
  metas:
    title:        "OpenParlamento - dati storici"
    robots:       "noindex,nofollow"
    googlebot:    "noarchive,nosnippet"
    description:  "Alcuni dati storici di Openparlamento"
  