# default values
all:
  # remote guard host
  # remote_guard_host:      'accesso.openpolis.it'
  remote_guard_host:      'accesso.openpolis.it'

  # cookies
  cookies:
    path:                 '/'
    domain:               'openpolis.it'
    sso_name:             'opSSO'
    remember_name:        'opRemember'
    remember_key_expiration_age: 604800 # (7 days)

  deppPropelActAsTaggableBehaviorPlugin:
    anonymous_tagging:           false
    allows_tagging_removal:      'self'
    tagging_removal_credentials: ['moderator']
    use_unique_triple_values:    true

  sfEmendPlugin:    
    user:
      cu_id_method:    getId
      profile_class:   OppUser
      name_method:     __toString
      allow_anonymous: false
    allowed_tags:
      a:              <a>
      em:             <em>
      i:              <i>
      p:              <p>
      strong:         <strong>

    
  deppPropelActAsCommentableBehaviorPlugin:    
    namespaces:
      frontend:       
      backend:        administrator
    count:
      enabled:        true
      method:         setsfCommentCount
      namespace:      frontend
    user:
      enabled:        true
      cu_id_method:   getId
      class:          OppUser
      name_method:    __toString
      email_method:   getEmail
      website_method: getUrlPersonalWebsite
    allowed_tags:
      a:              <a>
      blockquote:     <blockquote>
      code:           <code>
      em:             <em>
      i:              <i>
      p:              <p>
      strong:         <strong>

  nahoWikiPlugin:
    include_breadcrumbs:    off            # Include breadcrumbs slot (disable if you include the slot in your layout) ?
    include_pagename:       off            # Display page's name when viewing content ?
    include_toc:            off            # Display Table of Contents at top of every page

  comments:                enabled
  comments_use_ajax:       true
  comment_automoderation:  'captcha'    # comment automoderation; possible values are:
                                        # on: comments are not published until a moderator accepts them
                                        # first_post: the first comment of a user must be accepted, 
                                        #             subsequent posts are accepted automatically
                                        # off: comments are automatically accepted and published
                                        # captcha: comments are accepted and published, but requires a captcha (requires sfCaptcha)
  comment_mail_alert:      'on'         # send an email to the moderator when a content is posted. 
                                        # Possible values are:                                     
                                        # on: send an email for every posted comment               
                                        # moderated: send an email for every automoderated comment 
                                        # off: never send emails

  atto:
    pagination_limit:  30

  news_dropdown_limit: 7
  
  pagination:
    limit:    60

  voto:
    "1":     "Assente"
    "2":     "Astenuto"
    "3":     "Contrario"
    "4":     "Favorevole"
    "5":     "In missione"
    "6":     "Partecipante votazione non valida"
    "7":     "Presidente di turno"
    "8":     "Richiedente la votazione e non votante"
    "9":     "Voto segreto"

  iter_id:
    "decaduto":    "14"
    "convertito":  "63"

  mail_per_redazione:
    site_address: http://openparlamento.depplab.net/
