rendering: ~
web_debug: ~
security:  ~

# generally, you will want to insert your own filters here

highlight:
  class: sfSolrHighlightFilter
  
# filter that checks if a remember cookie exists and automatically logs the user in
rememberFilter:
  class: sfRemoteGuardRememberFilter

# filter that cheks if an sso cookie exists and automatically logs the user in
ssoFilter:
  class: sfRemoteGuardSsoFilter  

conditionalCache:
  class: conditionalCacheForAuthUsersFilter
  param:
    pages:
      - { module: atto, action: index }
      - { module: parlamentare, action: cosa }
      - { module: default, action: sottoscrizioniPro }

cache:     ~
common:    ~
flash:     ~
execution: ~
