#ddl:
#  url:   /ddl/:id
#  param: { module: ddl, action: index }

argomenti:
  url:   /argomenti
  param: { module: argomento, action: list }

argomento:
  url:   /argomento/:id
  param: { module: argomento, action: index }

teseo:
  url:   /teseo/:id
  param: { module: teseo, action: index }

votazioni:
  url:   /votazioni/:legislatura/:ramo/:page
  param: { module: votazione, action: list, legislatura: 16, ramo: entrambi, page: 1, display: false }

votazione:
  url:   /votazione/:id
  param: { module: votazione, action: index }

parlamentari:
  url:   /parlamentari/:legislatura/:carica
  param: { module: parlamentare, action: list, legislatura: 16, carica: Deputato, display: false }

parlamentare:
  url:   /parlamentare/:id
  param: { module: parlamentare, action: index }

sf_captcha:
  url:   /captcha/:rk
  param: { module: sfCaptcha, action: index, rk: 0 }

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*