blog_index:
  url: /blog
  param: { module: sfSimpleBlog, action: index }

blog_article_with_date:
  url: /blog/:year/:month/:day/:stripped_title
  param: { module: sfSimpleBlog, action: show }

blog_article:
  url: /blog/:stripped_title
  param: { module: sfSimpleBlog, action: show }

blog_tag:
  url: /blog/tag/:tag
  param: { module: sfSimpleBlog, action: showByTag }

  
monitoring_news:
  url: /monitoring_news/:user_token
  param: { module: monitoring, action: news}

monitoring_acts:
  url: /monitoring_acts/:user_token
  param: { module: monitoring, action: acts}

monitoring_politicians:
  url: /monitoring_politicians/:user_token
  param: { module: monitoring, action: politicians}

monitoring_tags:
  url: /monitoring_tags/:user_token
  param: { module: monitoring, action: tags }

addTagToMyMonitoredTags:
  url: /addTagToMyMonitoredTags/:name
  param: { module: monitoring, action: addTagToMyMonitoredTags }
  
removeTagFromMyMonitoredTags:
  url: /removeTagFromMyMonitoredTags/:name
  param: { module: monitoring, action: removeTagFromMyMonitoredTags }


news_tag:
  url: /news_tag/:name
  param: { module: news, action: tag }

news_atto:
  url:  /news_atto/:id
  param: { module: news, action: act }

news_parlamentare:
  url:  /news_parlamentare/:id
  param: { module: news, action: politician }

news_attiDisegni:
  url: /news_attiDisegni
  param: { module: news, action: disegniList}

news_attiDecreti:
  url: /news_attiDecreti
  param: { module: news, action: decretiList}

news_attiDecretiLegislativi:
  url: /news_attiDecretiLegislativi
  param: { module: news, action: decretiLegislativiList}

news_attiNonLegislativi:
  url: /news_attiNonLegislativi
  param: { module: news, action: attiNonLegislativiList}

news_votazioni:
  url: /news_votazioni
  param: { module: news, action: votazioni }

attiSearch:
  url: /attiSearch/:type/*
  param: { module: sfSolr, action: attiSearch }

attiDisegni:
  url: /attiDisegni
  param: { module: atto, action: disegnoList }
  
attiDecretiLegge:
  url: /attiDecretiLegge
  param: { module: atto, action: decretoList }

attiDecretiLegislativi:
  url: /attiDecretiLegislativi
  param: { module: atto, action: decretoLegislativoList }

attiNonLegislativi:
  url:   /attiNonLegislativi/:sort/:type
  param: { module: atto, action: attoNonLegislativoList, sort: data_pres, type: desc, display: false }

singolo_atto:
  url: /singolo_atto/:id
  param: { module: atto, action: index }


argomenti:
  url:   /argomenti    
  param: { module: argomento, action: list }
  
argomento_search:
  url:   /argomento_search/*
  param: { module: argomento, action: showFromSearch }

argomento:
  url:   /argomento/:triple_value/*
  param: { module: argomento, action: showAggiornamenti }

argomento_leggi:
  url:   /argomento_leggi/:triple_value/*
  param: { module: argomento, action: showLeggi }

argomento_nonleg:
  url:   /argomento_nonleg/:triple_value/*
  param: { module: argomento, action: showNonleg }

argomenti_per_categoria:
  url: /argomenti_per_categoria/*
  param: { module: argomento, action: ajaxTagsForTopTerm }

  
teseo:
  url:   /teseo/:id
  param: { module: teseo, action: index }

votazioniSearch:
  url: /votazioniSearch/*
  param: { module: sfSolr, action: votazioniSearch }

votazioni:
  url:   /votazioni/:sort/:type
  param: { module: votazione, action: list, sort: data, type: desc, display: false }

votazione:
  url:   /votazione/:id
  param: { module: votazione, action: index }
 

parlamentariSearch:
  url: /parlamentariSearch/*
  param: { module: sfSolr, action: parlamentariSearch }

parlamentari:
  url:   /parlamentari/:ramo/:sort/:type/*
  param: { module: parlamentare, action: list, ramo: camera, sort: nome, type: asc, display: false }

parlamentare:
  url:   /parlamentare/:id
  param: { module: parlamentare, action: cosa }

parlamentare_atti:
  url:  /parlamentare_atti/:id/:sort/:type/*
  param: { module: parlamentare, action: atti, sort: stato_last_date, type: desc }

parlamentare_voti:
  url:  /parlamentare_voti/:id/*
  param: { module: parlamentare, action: voti }

parlamentare_interventi:
  url:  /parlamentare_interventi/:id/*
  param: { module: parlamentare, action: interventi }

comparaParlamentari:
  url:   /parlamentare/comparaParlamentari/:id1/:id2/*
  param: { module: parlamentare, action: comparaParlamentari, id1: 0, id2: 0, display: false }    

get_logged_user:
  url: /get_logged_user
  param: { module: default, action: getLoggedUser }
  
sf_captcha:
  url:   /captcha/:rk
  param: { module: sfCaptcha, action: index, rk: 0 }

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*