api_pol_image:
  url: /get_pol_image/:key/:id
  param: { module: api, action: getPolImage }

api_atto:
  url: /fb_get_atto/:key/:opp_id.xml
  param: { module: api, action: atto }

api_elenco_atti:
  url: /fb_get_elenco_atti/:key/:data_inizio/:data_fine/*
  param: { module: api, action: elencoAtti }

api_parlamentare:
  url: /singolo_parlamentare/:key/:id
  param: { module: api, action: parlamentare }

api_parlamentari:
  url: /elenco_parlamentari/:key/:ramo/:infotype/:orderby/:ordertype
  param: { module: api, action: elencoParlamentari }

api_voti_chiave:
  url: /elenco_voti_chiave/:key/*
  param: { module: api, action: elencoVotiChiave }

api_voti_maggioranza_sotto:
  url: /elenco_voti_maggioranza_sotto/:key
  param: { module: api, action: elencoVotiMaggioranzaSotto }
  
api_votazione:
  url: /votazione/:key/:id
  param: { module: api, action: votazione }
  

dati_storici_interessi:
  url:   /interessi/*
  param: { module: datiStorici, action: interessi }

  
tesseramento:
  url: /tesseramento
  param: { module: static, action: tesseramento }
  
contatti:
  url: /contatti
  param: { module: static, action: contatti }

sottoscrizioni_pro:
  url: /sottoscrizioni_pro
  param: { module: default, action: sottoscrizioniPro }

sottoscrizione_premium_demo:
  url: /sottoscrizione_premium_demo
  param: { module: default, action: sottoscrizionePremiumDemo }
  
sottoscrizione_premium:
  url: /sottoscrizione_premium
  param: { module: default, action: sottoscrizionePremium }


grafico_distanze:
  url: /grafico_distanze/:tipo
  param: { module: default, action: graficoDistanze, tipo: 'votes_16_C' }

blog_index:
  url: /blog
  param: { module: sfSimpleBlog, action: index }

blog_article_with_date:
  url: /blog/:year/:month/:day/:stripped_title
  param: { module: sfSimpleBlog, action: show }

blog_article:
  url: /blog/:stripped_title
  param: { module: sfSimpleBlog, action: show }

blog_tag:
  url: /blog/tag/:tag
  param: { module: sfSimpleBlog, action: showByTag }


feed:
  url: /feed/
  param: { module: feed, action: lastGeneric }

feed_disegni:
  url: /feed/disegni
  param: { module: feed, action: lastDisegni }

feed_decreti:
  url: /feed/decreti
  param: { module: feed, action: lastDecreti }

feed_decretiLegislativi:
  url: /feed/decretiLegislativi
  param: { module: feed, action: lastDecretiLegislativi }

feed_attiNonLegislativi:
  url: /feed/attiNonLegislativi
  param: { module: feed, action: lastAttiNonLegislativi }
  
feed_politico:
  url: /feed/politico/:id
  param: { module: feed, action: lastPolitico }

feed_politico_radicali:
  url: /feed/politico_radicali/:id
  param: { module: feed, action: lastPoliticoRadicali }

feed_atto:
  url: /feed/atto/:id
  param: { module: feed, action: lastAtto }


monitoring_news:
  url: /monitoring_news/:user_token/*
  param: { module: monitoring, action: news}

monitoring_acts:
  url: /monitoring_acts/:user_token/*
  param: { module: monitoring, action: acts}

monitoring_politicians:
  url: /monitoring_politicians/:user_token
  param: { module: monitoring, action: politicians}

monitoring_tags:
  url: /monitoring_tags/:user_token
  param: { module: monitoring, action: tags }

monitoring_alerts:
  url: /monitoring_alerts/:user_token
  param: { module: monitoring, action: alerts }  

addTagToMyMonitoredTags:
  url: /addTagToMyMonitoredTags/:name
  param: { module: monitoring, action: addTagToMyMonitoredTags }
  
removeTagFromMyMonitoredTags:
  url: /removeTagFromMyMonitoredTags/:name
  param: { module: monitoring, action: removeTagFromMyMonitoredTags }

news_home:
  url: /news_home/*
  param: { module: news, action: homeAll }
  
news_tag:
  url: /news_tag/:id/*
  param: { module: news, action: tag }

news_atto:
  url:  /news_atto/:id/*
  param: { module: news, action: act }

news_parlamentare:
  url:  /news_parlamentare/:id/*
  param: { module: news, action: politician }

news_attiDisegni:
  url: /news_attiDisegni
  param: { module: news, action: disegniList}

news_attiDecreti:
  url: /news_attiDecreti
  param: { module: news, action: decretiList}

news_attiDecretiLegislativi:
  url: /news_attiDecretiLegislativi
  param: { module: news, action: decretiLegislativiList}

news_attiNonLegislativi:
  url: /news_attiNonLegislativi
  param: { module: news, action: attiNonLegislativiList}

news_votazioni:
  url: /news_votazioni
  param: { module: news, action: votazioni }
  
news_comunita:
  url: /news_comunita
  param: { module: news, action: comunita }  


attiSearch:
  url: /attiSearch/:type/*
  param: { module: sfSolr, action: attiSearch }

attiDisegni:
  url: /attiDisegni/*
  param: { module: atto, action: disegnoList }
  
attiDecretiLegge:
  url: /attiDecretiLegge/*
  param: { module: atto, action: decretoList }

attiDecretiLegislativi:
  url: /attiDecretiLegislativi/*
  param: { module: atto, action: decretoLegislativoList }

attiNonLegislativi:
  url:   /attiNonLegislativi/:sort/:type
  param: { module: atto, action: attoNonLegislativoList, sort: data_pres, type: desc, display: false }

singolo_atto:
  url: /singolo_atto/:id
  param: { module: atto, action: index }

widget_atto:
    url: /widget_atto
    param: { module: atto, action: widget }   
  
commenti_atto:
  url: /commenti_atto/:id
  param: { module: atto, action: commenti }

documento:
  url: /atto/documento/id/:id
  param: { module: atto, action: documento }

argomenti:
  url:   /argomenti    
  param: { module: argomento, action: list }
  
argomento_search:
  url:   /argomento_search/*
  param: { module: argomento, action: showFromSearch }

argomento:
  url:   /argomento/:triple_value/*
  param: { module: argomento, action: showAggiornamenti }

argomento_leggi:
  url:   /argomento_leggi/:triple_value/*
  param: { module: argomento, action: showLeggi }

argomento_nonleg:
  url:   /argomento_nonleg/:triple_value/*
  param: { module: argomento, action: showNonleg }

argomento_sioccupanodi:
  url:   /argomento_sioccupanodi/:triple_value/:ramo/*
  param: { module: argomento, action: listSiOccupanoDi }
  
argomenti_actionaid:
  url:   /argomenti_actionaid/:ramo/*
  param: { module: argomento, action: listClassificaActionAid }

argomenti_enel:
  url:   /argomenti_enel/:ramo/*
  param: { module: argomento, action: listClassificaEnel }  

argomenti_per_categoria:
  url: /argomenti_per_categoria/*
  param: { module: argomento, action: ajaxTagsForTopTerm }

emendamenti_atto:
  url: /emendamenti_atto/:id/*
  param: { module: emendamento, action: index }

singolo_emendamento:
  url: /emendamento/:id
  param: { module: emendamento, action: show }

commenti_emendamento:
  url: /commenti_emendamento/:id
  param: { module: emendamento, action: commenti }
  
teseo:
  url:   /teseo/:id
  param: { module: teseo, action: index }

votazioniSearch:
  url: /votazioniSearch/*
  param: { module: sfSolr, action: votazioniSearch }
  
votichiave:
  url:   /votazioni/keyvotes
  param: { module: votazione, action: keyvotes }
  
maggioranzaSotto:
  url:   /votazioni/maggioranzaSotto/:sort/:type/*
  param: { module: votazione, action: maggioranzaSotto, sort: data, type: desc, display: false }  
  
votazioni:
  url:   /votazioni/:sort/:type/*
  param: { module: votazione, action: list, sort: data, type: desc, display: false }

votazione:
  url:   /votazione/:id
  param: { module: votazione, action: index }

commenti_votazione:
  url: /commenti_votazione/:id
  param: { module: votazione, action: commenti }
 

parlamentariSearch:
  url: /parlamentariSearch/*
  param: { module: sfSolr, action: parlamentariSearch }

parlamentari_nuovo_indice:
  url: /parlamentari_nuovo_indice/:ramo
  param: { module: parlamentare, action: listNuovoIndice, ramo: camera }
  
parlamentari:
#  url:   /parlamentari/:ramo/*
  url:   /parlamentari/:ramo/:sort/:type/*
  param: { module: parlamentare, action: list, ramo: camera, sort: nome, type: asc, display: false }

parlamentare:
  url:   /parlamentare/:id
  param: { module: parlamentare, action: cosa }

parlamentare_atti:
  url:  /parlamentare_atti/:id/:sort/:type/*
  param: { module: parlamentare, action: atti, sort: stato_last_date, type: desc }

parlamentare_voti:
  url:  /parlamentare_voti/:id/*
  param: { module: parlamentare, action: voti }

parlamentare_interventi:
  url:  /parlamentare_interventi/:id/*
  param: { module: parlamentare, action: interventi }
  
parlamentare_emendamenti:
  url:  /parlamentare_emendamenti/:id/*
  param: { module: parlamentare, action: emendamenti }  

parlamentari_tabella_delta:
  url:   /tabella_delta/:data/:mesi/:ramo/:dato
  param: { module: parlamentare, action: tabellaDelta }
  
comparaDeputati:
  url:   /parlamentare/comparaDeputati/:id1/:id2/:ramo/*
  param: { module: parlamentare, action: comparaDeputati, id1: 0, id2: 0, ramo: 1, display: false }    

get_logged_user:
  url: /get_logged_user
  param: { module: default, action: getLoggedUser }
  
sf_captcha:
  url:   /captcha/:rk
  param: { module: sfCaptcha, action: index, rk: 0 }
  
# pagine statiche
progetto:
  url:  /progetto
  param: { module: static, action: progetto }

faq:
  url:  /faq
  param: { module: static, action: faq }


# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
