#ddl:
#  url:   /ddl/:id
#  param: { module: ddl, action: index }

#atto:
#  url:   /atto/:id
#  param: { module: atto, action: index }

monitoring_news:
  url: /monitoring_news/:user_token
  param: { module: monitoring, action: news}

monitoring_acts:
  url: /monitoring_acts/:user_token
  param: { module: monitoring, action: acts}

monitoring_politicians:
  url: /monitoring_politicians/:user_token
  param: { module: monitoring, action: politicians}

monitoring_tags:
  url: /monitoring_tags/:user_token
  param: { module: monitoring, action: tags }

news_tag:
  url: /news_tag/:id
  param: { module: news, action: tag }

news_atto:
  url:  /news_atto/:id
  param: { module: news, action: act }

news_parlamentare:
  url:  /news_parlamentare/:id
  param: { module: news, action: politician }

attiNonLegislativi:
  url:   /atti_non_legislativi/:sort/:type
  param: { module: atto, action: attoNonLegislativoList, sort: data_pres, type: desc, display: false }

atto:
  url: /atto/:id
  param: { module: atto, action: index }
    
argomenti:
  url:   /argomenti
  param: { module: argomento, action: list }

argomento:
  url:   /argomento/:id
  param: { module: argomento, action: index }

tag:
  url:  /tag/:tag_name
  param: { module: argomento, action: index }

teseo:
  url:   /teseo/:id
  param: { module: teseo, action: index }

votazioni:
  url:   /votazioni/:sort/:type
  param: { module: votazione, action: list, sort: data, type: desc, display: false }

votazione:
  url:   /votazione/:id
  param: { module: votazione, action: index }

parlamentari:
  url:   /parlamentari/:ramo/:sort/:type
  param: { module: parlamentare, action: list, ramo: camera, sort: nome, type: asc, display: false }

parlamentare:
  url:   /parlamentare/:id
  param: { module: parlamentare, action: index }

sf_captcha:
  url:   /captcha/:rk
  param: { module: sfCaptcha, action: index, rk: 0 }

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*