# Define any application specific rules to your models here
# such as routing, partials, etc.

SolrIndex:
  models:
    Tag:
      route: argomento/showAggiornamenti?triple_value=%triple_value%
      partial: argomento/searchResult
      alertPartial: argomento/alert
    OppAtto:
      route: atto/index?id=%propel_id%
      partial: atto/searchResult
      alertPartial: atto/alert
    OppDocumento:
      route: atto/documento?id=%propel_id%
      partial: atto/searchResultDoc
      alertPartial: atto/alertDoc
    OppVotazione:
      route: votazione/index?id=%propel_id%
      partial: votazione/searchResult
      alertPartial: votazione/alert
    OppPolitico:
      route: parlamentare/cosa?id=%propel_id%
      partial: parlamentare/searchResult
      alertPartial: parlamentare/alert
    OppResoconto:
      route:   -
      partial: resoconto/searchResult
      alertPartial: resoconto/alert
    OppEmendamento:
      route: emendamento/show?id=%propel_id%
      partial: emendamento/searchResult
      alertPartial: emendamento/alert
    OppEsitoSeduta:
      route: -
      partial: atto/searchResultEsito
      alertPartial: atto/alertEsito
      
