default:
  http_metas:
    content-type: text/html

  metas:
    title:        OpenParlamento
    robots:       index, follow
    description:  Il progetto Openpolis per il monitoring del Parlamento
    keywords:     Openparlamento, Openpolis, monitoring parlamentare, monitoring parlamento, controllo parlamentare, controllo parlamento
    language:     it

  stylesheets:    [screen, combobox_openpolis]

  javascripts:    []

  has_layout:     on
  layout:         layout
