default:
  http_metas:
    content-type: "text/html"

  metas:
    title:        "OpenParlamento"
    robots:       "<?php echo sfConfig::get('sf_site_url') == 'parlamento.openpolis.it' ? 'index, follow' : 'noindex, nofollow' ?>"
    <?php echo (sfConfig::get('sf_site_url') != 'parlamento.openpolis.it' ? 'googlebot: noarchive,nosnippet' : '') . "\n" ?>
    description:  "Il progetto Openpolis per il monitoring del Parlamento"
    keywords:     "Openparlamento, Openpolis, monitoring parlamentare, monitoring parlamento, controllo parlamentare, controllo parlamento"
    language:     it

  stylesheets:    [screen, combobox_openpolis]

  javascripts:    [<?php echo  sfConfig::get('sf_js_google_load')=='true'?'http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min.js':'fe/jquery.js'?>, fe/jquery.combobox.min.js, fe/jquery.ifixpng2.min.js, fe/openparlamento.lists.js]

  has_layout:     on
  layout:         layout
