default:
  http_metas:
    content-type: text/html

  metas:
    title:        OPENPARLAMENTO
    robots:       index, follow
    description:  Il progetto Openpolis per il monitoring del Parlamento
    keywords:     Openparlamento, Openpolis, monitoring parlamentare, monitoring parlamento, controllo parlamentare, controllo parlamento
    language:     it

  stylesheets:    [screen, combobox_openpolis]

  javascripts:    [fe/jquery-1.2.6.js, fe/jquery.combobox.js, fe/jquery.pngFix.js, fe/openparlamento.lists.js]

  has_layout:     on
  layout:         layout
