sottoscrizionePremiumDemoSuccess:
  metas:
    title:        "Adesione al servizio Premium - OpenParlamento"

graficoDistanzeSuccess:
  javascripts:    [http://ajax.googleapis.com/ajax/libs/swfobject/2.1/swfobject.js]  

getLoggedUserSuccess:
  has_layout:     off
  http_metas:
      content-type: "text"
