all:
  propel:
    class:          sfPropelDatabase
    param:
      phptype:      mysql
      hostspec:     localhost
      database:     openparlamento
      username:     "op7941x"
      password:     "ranz7211"
      compat_assoc_lower:  true
      compat_rtrim_string: true