propel:  

  opp_appoggio:
    id:
    carica_id:        { type: integer, required: true, index: true, foreignTable: opp_carica, foreignReference: id, onDelete: CASCADE }
    aka:              { type: varchar(60) }
    tipologia:        { type: integer }
    legislatura:      { type: tinyint }


  opp_atto:
    id:
    parlamento_id:      { type: integer }
    tipo_atto_id:       { type: integer, required: true, index: true, foreignTable: opp_tipo_atto, foreignReference: id, onDelete: CASCADE }
    ramo:               { type: char, size: 1 }
    numfase:            { type: varchar(255) }
    legislatura:        { type: integer }
    data_pres:          { type: date, index: true }
    data_agg:           { type: date, index: true }
    titolo:             { type: longvarchar }
    titolo_aggiuntivo:  { type: longvarchar }
    iniziativa:         { type: integer }
    stato_cod:          { type: char, size: 2, index: multiple }
    stato_fase:         { type: varchar(255) }
    stato_last_date:    { type: timestamp }
    completo:           { type: boolean }
    descrizione:        { type: clob }
    seduta:             { type: integer }
    pred:               { type: integer }
    succ:               { type: integer }
    voto_medio:         { type: float }
    ut_fav:             { type: integer }
    ut_contr:           { type: integer }
    nb_commenti:        { type: integer, required: true, default: 0 }
    n_monitoring_users: { type: integer, required: true, default: 0, index: multiple }
    n_interventi:       { type: integer, required: true, default: 0, index: multiple }
    created_at:

  opp_atto_has_iter:
    id:
    atto_id:          { type: integer, required: true, index: true, foreignTable: opp_atto, foreignReference: id, onDelete: CASCADE }
    iter_id:          { type: integer, required: true, index: true, foreignTable: opp_iter, foreignReference: id, onDelete: CASCADE }
    data:             { type: date }
    created_at:

  opp_atto_has_sede:
    atto_id:          { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_atto, foreignReference: id, onDelete: CASCADE }
    sede_id:          { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_sede, foreignReference: id, onDelete: CASCADE }
    tipo:             { type: varchar(255) }
    created_at:

  opp_atto_has_teseo:
    atto_id:          { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_atto, foreignReference: id, onDelete: CASCADE }
    teseo_id:         { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_teseo, foreignReference: id, onDelete: CASCADE }


  opp_carica:
    id:               { type: integer, required: true, primaryKey: true, index: true }    # e' il content_id di openpolis.op_institution_charge
    politico_id:      { type: integer, required: true, index: true, foreignTable: opp_politico, foreignReference: id, onDelete: CASCADE }
    tipo_carica_id:   { type: integer, required: true, index: true, foreignTable: opp_tipo_carica, foreignReference: id }
    carica:           { type: varchar(30) }
    data_inizio:      { type: date }
    data_fine:        { type: date }
    legislatura:      { type: tinyint }
    circoscrizione:   { type: varchar(60) }
    presenze:         { type: integer }
    assenze:          { type: integer }
    missioni:         { type: integer }
    parliament_id:    { type: integer }
    indice:           { type: float }
    scaglione:        { type: integer }
    posizione:        { type: integer }
    media:            { type: float }
    ribelle:          { type: integer }
    created_at:

  opp_carica_has_atto:
    atto_id:          { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_atto, foreignReference: id, onDelete: CASCADE }
    carica_id:        { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_carica, foreignReference: id, onDelete: CASCADE }
    tipo:             { type: varchar(255), primaryKey: true, index: true }
    data:             { type: date }
    url:              { type: longvarchar }
    created_at:

  opp_carica_has_gruppo:
    carica_id:        { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_carica, foreignReference: id, onDelete: CASCADE }
    gruppo_id:        { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_gruppo, foreignReference: id, onDelete: CASCADE } 
    data_inizio:      { type: date }
    data_fine:        { type: date }
    presenze:         { type: integer }
    ribelle:          { type: integer }
    created_at:
    
  opp_categoria:
    id:
    denominazione:             { type: varchar(255) }
    
  opp_categoria_has_tt:
    categoria_id:    { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_categoria, foreignReference: id, onDelete: CASCADE }
    teseott_id:      { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_teseott, foreignReference: id, onDelete: CASCADE }  
 
  opp_similarita:
    carica_from_id:     { type: integer, required: true, primaryKey: true, foreignTable: opp_carica, foreignReference: id, onDelete: CASCADE }
    carica_to_id:       { type: integer, required: true, primaryKey: true, foreignTable: opp_carica, foreignReference: id, onDelete: CASCADE }
    voting_similarity:  { type: float, index: true, required: true, default: 0 }
    signing_similarity: { type: float, index: true, required: true, default: 0 }
    
  opp_documento:
    id:
    atto_id:          { type: integer, required: true, index: true, foreignTable: opp_atto, foreignReference: id, onDelete: CASCADE }
    data:             { type: date }
    titolo:           { type: varchar(512) }
    # stripped_titolo:  { type: varchar(512) }
    testo:            { type: clob }
    file_pdf:         { type: blob }
    url_testo:        { type: varchar(1024) }
    url_pdf:          { type: varchar(1024) }
    created_at:
    
  opp_gruppo:
    id:
    nome:             { type: varchar(255) }
    acronimo:         { type: varchar(80) }

  opp_intervento:
    id:
    atto_id:          { type: integer, required: true, index: true, foreignTable: opp_atto, foreignReference: id, onDelete: CASCADE }
    carica_id:        { type: integer, required: true, index: true, foreignTable: opp_carica, foreignReference: id, onDelete: CASCADE }
    sede_id:          { type: integer, required: true, index: true, foreignTable: opp_sede, foreignReference: id, onDelete: CASCADE }
    tipologia:        { type: varchar(255) }
    url:              { type: longvarchar }
    data:             { type: date }
    numero:           { type: integer }
    ap:               { type: tinyint }
    created_at:

  opp_iter:
    id:
    fase:             { type: varchar(255) }
    concluso:         { type: boolean }
    cache_cod:        { type: char, size: 2 }

  opp_legge:
    id:
    atto_id:         { type: integer, required: true, index: true, foreignTable: opp_atto, foreignReference: id, onDelete: CASCADE }
    numero:          { type: integer }
    data:            { type: date }
    url:             { type: longvarchar }
    gu:              { type: longvarchar }

  opp_legislatura_has_gruppo:
    legislatura:      { type: tinyint, required: true, primaryKey: true, index: true }  
    ramo:             { type: char, size: 1, required: true, primaryKey: true, index: true }
    gruppo_id:        { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_gruppo, foreignReference: id, onDelete: CASCADE }

  opp_policy:
    id:
    titolo:           { type: varchar(255) }
    descrizione:      { type: longvarchar }
    provvisoria:      { type: boolean }

  opp_policy_has_votazione:
    policy_id:        { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_policy, foreignReference: id, onDelete: CASCADE }
    votazione_id:     { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_votazione, foreignReference: id, onDelete: CASCADE }
    voto:             { type: varchar(25) }
    strong:           { type: boolean }

  opp_politico:
    id:                 { type: integer, required: true, primaryKey: true, index: true } # politician_id di openpolis 
    nome:               { type: varchar(30) }
    cognome:            { type: varchar(30) }
    n_monitoring_users: { type: integer, required: true, default: 0, index: multiple }
    
  opp_sede:
    id:
    ramo:             { type: varchar(255) }
    denominazione:    { type: varchar(255) }
    legislatura:      { type: integer }
    tipologia:        { type: varchar(255) }
    codice:           { type: varchar(255) }

  opp_seduta:
    id:
    data:             { type: date }
    numero:           { type: integer, required: true }
    ramo:             { type: char, size: 1, required: true }
    legislatura:      { type: tinyint, required: true }
    url:              { type: longvarchar }
    is_imported:      { type: tinyint, required: true, default: 0 }
    

  opp_tipo_atto:
   id:  
   denominazione:     { type: varchar(60) }
   descrizione:       { type: varchar(60) }
   spiegazione:       { type: longvarchar }

  opp_tipo_carica:
   id:  
   nome:              { type: varchar(255) }
   
  opp_tipo_relazione:
   id:  
   denominazione:     { type: varchar(255) }

  opp_relazione_atto:
    id:
    atto_from_id:      { type: integer, required: true, index: true, foreignTable: opp_atto, foreignReference: id, onDelete: CASCADE }
    atto_to_id:        { type: integer, required: true, index: true, foreignTable: opp_atto, foreignReference: id, onDelete: CASCADE }
    tipo_relazione_id: { type: integer, required: true, index: true, foreignTable: opp_tipo_relazione, foreignReference: id, onDelete: CASCADE }
    descrizione:       { type: varchar(60) }
    data:              { type: date }
    created_at:



  opp_teseo:
    id:
    tipo_teseo_id:    { type: integer, required: true, index: true, foreignTable: opp_tipo_teseo, foreignReference: id }
    denominazione:    { type: longvarchar }
    ns_denominazione: { type: longvarchar }
    teseott_id:       { type: integer }
    tt:               { type: integer }

  opp_teseo_has_teseott:
   teseo_id:          { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_teseo, foreignReference: id, onDelete: CASCADE }
   teseott_id:        { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_teseott, foreignReference: id, onDelete: CASCADE }

  opp_tag_has_tt:
    tag_id:          { type: integer, required: true, primaryKey: true, index: true, foreignTable: sf_tag, foreignReference: id, onDelete: CASCADE }
    teseott_id:      { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_teseott, foreignReference: id, onDelete: CASCADE }

  # dummy (or patch), to have the admin generator work symfony propel-init-admin 
  # this can (must) be removed after the invocation of the symfony propel-init-admin command
  # the package param is important, since the classes must be generated in the plugins directory
  #sf_tag:
  #  _attributes:      { phpName: Tag, package: plugins.deppPropelActAsTaggableBehaviorPlugin.lib.model }
  #  id:               { phpName: ID, type: integer, required: true, primaryKey: true, autoincrement: true }
  #  name:             varchar(255)
  #  n_monitoring_users: { type: integer, required: true, default: 0 }
  #  is_tmp:           { type: tinyint, required: true, default: 1 }
  #  is_triple:        { type: tinyint }
  #  triple_namespace: varchar(100)
  #  triple_key:       varchar(100)
  #  triple_value:     varchar(255)
  #  _uniques:
  #    name:           [name]
  #  _indexes:
  #    triple1:        [triple_namespace]
  #    triple2:        [triple_key]
  #    triple3:        [triple_value]


  opp_teseott:
    id:
    denominazione:    { type: longvarchar }
    ns_denominazione: { type: longvarchar }
    teseo_senato:     { type: integer }

  opp_tipo_teseo:
    id:
    tipo:             { type: varchar(50) }


  opp_user: 
    id:                      { type: integer, required: true, index: unique, primaryKey: true }
    location_id:             { type: integer }
    first_name:              { type: varchar(100) }
    last_name:               { type: varchar(100) }
    nickname:                { type: varchar(16) }
    is_active:               { type: boolean, required: true, default: 0 }
    email:                   { type: varchar(100), required: true, default: '' }
    picture:                 { type: varbinary }
    url_personal_website:    { type: varchar(255) }
    notes:                   { type: longvarchar }
    has_paypal:              { type: integer, default: 0 }
    wants_newsletter:        { type: tinyint, default: 0 } 
    public_name:             { type: tinyint, required: true, default: 1 }
    votes:                   { type: integer, default: 0 }
    comments:                { type: integer, default: 0 }
    discussions:             { type: integer, default: 0 }
    last_contribution:       { type: timestamp }
    n_monitored_tests:       { type: integer, default: 0 }
    n_monitored_tags:        { type: integer, default: 0 }
    n_monitored_attos:       { type: integer, default: 0 }
    n_monitored_politicos:   { type: integer, default: 0 }
    n_monitored_objects:     { type: integer, default: 0 }
    n_max_monitored_tags:    { type: integer, default: 5 }
    n_max_monitored_items:   { type: integer, default: 10 }

  opp_votazione:
    id:
    seduta_id:          { type: integer, required: true, index: true, foreignTable: opp_seduta, foreignReference: id, onDelete: CASCADE }
    numero_votazione:   { type: smallint, required: true }   
    titolo:             { type: longvarchar }
    titolo_aggiuntivo:  { type: longvarchar }
    presenti:           { type: integer }
    votanti:            { type: integer }
    maggioranza:        { type: integer }
    astenuti:           { type: integer }
    favorevoli:         { type: integer }
    contrari:           { type: integer }
    esito:              { type: varchar(20) }
    ribelli:            { type: integer }
    margine:            { type: integer }
    tipologia:          { type: varchar(20) }
    descrizione:        { type: longvarchar }
    url:                { type: varchar(255) }
    finale:             { type: integer, required: true, default: 0 }
    nb_commenti:        { type: integer, required: true, default: 0 }
    is_imported:        { type: tinyint, required: true, default: 0 }
    

  opp_votazione_has_atto:
    votazione_id:     { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_votazione, foreignReference: id, onDelete: CASCADE }
    atto_id:          { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_atto, foreignReference: id, onDelete: CASCADE }
    created_at:

  opp_votazione_has_carica:
    votazione_id:     { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_votazione, foreignReference: id, onDelete: CASCADE }
    carica_id:        { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_carica, foreignReference: id, onDelete: CASCADE }
    voto:             { type: varchar(40) }
    ribelle:          { type: tinyint, required: true, default: 0 }

  opp_votazione_has_gruppo:
    votazione_id:     { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_votazione, foreignReference: id, onDelete: CASCADE }
    gruppo_id:        { type: integer, required: true, primaryKey: true, index: true, foreignTable: opp_gruppo, foreignReference: id, onDelete: CASCADE }
    voto:             { type: varchar(40) }
    
  sf_test_object:
    _attributes:       { phpName: sfTestObject }
    id:
    name:              { type: varchar(50), required: true, default: 'Nessun nome' }
    sf_comment_count:  { type: integer, required: true, default: 0 }

  sf_test_bookmarkable:
    _attributes:       { phpName: sfTestBookmarkable }
    id:
    title:             { type: varchar(50), required: true, default: 'Nessun titolo' }

  sf_test_votable:
    _attributes:       { phpName: sfTestVotable }
    id:
    title:             { type: varchar(50), required: true, default: 'Nessun titolo' }
    voto_medio:        { type: float }
    ut_fav:            { type: integer }
    ut_contr:          { type: integer }

  sf_test_monitorable:
    _attributes:         { phpName: sfTestMonitorable }
    id:
    title:               { type: varchar(50), required: true, default: 'Titolo monitorabile' }
    n_monitoring_users:  { type: integer, required: true, default: 0 }
    
  sf_test_generator:
    _attributes:         { phpName: sfTestGenerator }
    id:
    title:               { type: varchar(50), required: true, default: 'Titolo generatore'}
    test_date:           { type: timestamp }
    created_at:
    monitorable_id:      { type: integer, required: true, index: true, foreignTable: sf_test_monitorable, foreignReference: id, onDelete: CASCADE }
    
  sf_test_images:
    _attributes:       { phpName: sfTestImages }
    id:
    picture:           { type: varbinary }

