# parametri per la connessione al server solr e  sul tipo di query
task:
  query_debug_level: 1

dev:
  query_debug_level: 2

all:
  query_debug_level: 0
  query_handler: dismax
  index_dir: "/usr/local/solr-tomcat/solr_op_openparlamento17/data/index/"
  connection:
    host: "localhost"
    port: "8080"
    path: "/solr_op_openparlamento17"
    