generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      OppVotazione
    theme:            default

    list:
      title:          Elenco votazioni
      display:        [_ramo, _data, esito, margine, ribelli]
#      peer_method:    doSelectJoinOppSeduta
      filters:        [legislatura, ramo]