generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      OppVotazione
    theme:            default

    fields:          
      titolo:            { name: 'Titolo' }
      titolo_aggiuntivo: { name: 'Titolo aggiuntivo' }
    

    list:
      title:          Elenco votazioni
      layout:         stacked
      display:        [=titolo, titolo_aggiuntivo]
      params:          |
         <strong>%%=titolo%%</strong><br/>
         Titolo aggiuntivo: <strong>%%titolo_aggiuntivo%%</strong>
      filters:        [legislatura, titolo]
      
    edit: 
      title:           "Modifica titolo aggiuntivo atto %%titolo%%"
      display:        
        "Atto":         [titolo, titolo_aggiuntivo]
      fields: 
        titolo:            { name: "Titolo risultante", params: "disabled=true size=60x5" }
        titolo_aggiuntivo: { name: 'Titolo aggiuntivo', params: "size=60x5" }
      actions:
        _list:          -
        _save:          -
        _delete:        none
    