indexSuccess:
  javascripts:    ["/js/jquery-1.4.3.min.js", "/js/jquery.tablesorter.min.js"]
  stylesheets:    ["/css/tablesorter_themes/blue/style.css"]
  
commentiSuccess:
  javascripts:    [-*, prototype]
  
parlamentariSalvaSuccess:
  javascripts:    ["/js/jquery-1.4.3.min.js", "/js/jquery.tablesorter.min.js"]
  stylesheets:    ["/css/tablesorter_themes/blue/style.css"]
  
parlamentariSottoSuccess:
  javascripts:    ["/js/jquery-1.4.3.min.js", "/js/jquery.tablesorter.min.js"]
  stylesheets:    ["/css/tablesorter_themes/blue/style.css"]  