disegnoList:
  enabled: on

decretoList:
  enabled: on
  
attoNonLegislativoList:
  enabled: on
  
decretoLegislativoList:
  enabled: on

_inevidenza:
  enabled: on
  lifetime: 30
  
all:
  with_layout: false
  lifetime: 3600
