indexSuccess:
  javascripts:    [-*, fe/jquery-1.2.6.pack.js, fe/jquery.combobox.js, fe/jquery.pngFix.js, fe/openparlamento.lists.js, fe/jquery.autocomplete.min.js]
  stylesheets:    [-*, screen, monitoring, jquery.autocomplete.css]

documentoSuccess:
  javascripts:    [/sfEmendPlugin/emend.boot.js]
  stylesheets:    [-*, screen, testo_atto]

all:
  javascripts:    
    - fe/jquery-1.2.6.pack.js
    - fe/jquery.combobox.js
    - fe/jquery.pngFix.js
    - fe/openparlamento.lists.js
    - fe/jquery.bgiframe.min.js
    - fe/jquery.ajaxQueue.js
    - fe/jquery.autocomplete.min.js
  stylesheets:    [monitoring, jquery.autocomplete.css]

