commentiSuccess:
  javascripts:    [-*, prototype]
  stylesheets:    [-*, screen.css]


indexSuccess:
  stylesheets:    [-*, screen.css, monitoring, jquery.autocomplete.css]

documentoSuccess:
  javascripts:    [-*]
  stylesheets:    [-*, screen.css, testo_atto]
  layout:         layoutDoc

widgetSuccess:
  has_layout: false

all:
  javascripts:    
    - fe/jquery.bgiframe.min.js
    - fe/jquery.ajaxQueue.js
    - fe/jquery.autocomplete.min.js
  stylesheets:    [monitoring, jquery.autocomplete.css]

