all:
  stylesheets:    [monitoring]

newsSuccess:
  javascripts:    [jquery.js, fe/jquery.combobox.js, fe/jquery.pngFix.js, fe/openparlamento.lists.js]

actsSuccess:
  javascripts:    [jquery.js, fe/jquery.combobox.js, fe/jquery.pngFix.js, fe/openparlamento.lists.js]